/* Proposed C4 model. Local explanatory data: no credentials, SDK calls or requests. */
(() => {
  'use strict';
  const sources = {
    proposal: { label: 'Propuesta y decisiones de arquitectura', url: '../docs/propuesta-arquitectura.md' },
    technology: { label: 'Opciones tecnológicas y límites', url: '../docs/opciones-tecnologicas.md' },
    resilience: { label: 'Integridad, recuperación y casos adversos', url: '../docs/revision-resiliencia-datos-pos.md' },
    providers: { label: 'Proveedores, periféricos y homologación', url: '../docs/extensibilidad-proveedores-dispositivos.md' },
    evidence: { label: 'Catálogo del sistema actual: evidencia por repositorio', url: '../docs/catalogo-integraciones-actuales.md' },
    operations: { label: 'Operación de caja y evolución', url: '../docs/operacion-caja-y-evolucion.md' },
    c4: { label: 'Guía de estas vistas C4', url: '../docs/c4-arquitectura-propuesta.md' },
  };
  const nodes = {};
  function node(id, name, type, technology, summary, ownership, offline, detail, refs = ['proposal', 'technology']) {
    nodes[id] = { id, name, type, technology, summary, ownership, offline, detail, sources: refs.map(key => sources[key]) };
  }
  node('cashier', 'Cajero', 'Persona', 'Operación humana', 'Vende, cobra y gestiona su turno.', 'Ejecuta operaciones con permisos; no administra la base.', 'Acceso local y operaciones habilitadas según vigencia, permisos y política offline.', 'Usa el cliente del puesto. Abrir o cerrar sesión de usuario no equivale a abrir o cerrar el turno de caja.');
  node('supervisor', 'Supervisor de sucursal', 'Persona', 'Operación humana', 'Autoriza excepciones y revisa cierres.', 'Responsable operativo; los comandos mantienen autorización y auditoría.', 'Solo facultades previamente habilitadas; sin inventar autorización central.', 'Consulta resultados, autoriza acciones permitidas y resuelve incidencias con evidencia.');
  node('support', 'Operación de plataforma', 'Persona', 'Soporte autorizado', 'Supervisa sincronización y recuperación.', 'Administra configuración y reintentos auditados; no corrige dinero con SQL libre.', 'Consulta evidencia local; la plataforma de país puede estar inaccesible sin WAN.', 'Programa cargas y ventanas, supervisa atrasos, coordina restauraciones y conciliaciones.');
  node('pos', 'POS corporativo', 'Sistema de software', 'Plataforma de caja', 'Opera sucursales e integra cada país.', 'La venta nace en sucursal; país mantiene la proyección consolidada.', 'Perfil inicial: WAN caída con LAN y escritor de sucursal disponibles.', 'Sistema objetivo común para Chile, Perú y España. Cliente Angular + Tauri aceptado como dirección; backend, datos y topología son recomendaciones por validar.');
  node('erp', 'ERP del país', 'Sistema externo', 'CL: AX · ES: Gira · PE: custom', 'Recibe y concilia documentos financieros.', 'Autoridad financiera según contrato de cada país; no la base de ventas del POS.', 'Su indisponibilidad deja integración pendiente; no revierte una venta local confirmada.', 'Chile usa Dynamics AX on-premise. Gira en España y custom en Perú son antecedentes; versión, interfaces y capacidades deben confirmarse. No se afirma que exista el adaptador objetivo en producción.', ['proposal', 'evidence']);
  node('masters', 'Fuentes de maestros y precios', 'Sistema externo', 'Interfaces por confirmar', 'Publica datos y reglas autorizados.', 'Propietario por dato y país pendiente: no se asigna al ERP por defecto.', 'Sin WAN se usa la versión local vigente dentro de la política autorizada.', 'Catálogo, impuestos, precios y promociones deben tener responsable, contrato, versión y vigencia. La fuente de precios no se sustituye por una tabla editada libremente en cada caja.', ['proposal', 'operations']);
  node('payments', 'Proveedor de pagos', 'Sistema externo', 'API / SDK según proveedor', 'Autoriza o informa el resultado del pago.', 'El proveedor mantiene el efecto financiero; POS registra intento, referencia y resultado.', 'Disponibilidad y modo offline por homologar. Un timeout puede dejar resultado desconocido.', 'Pago, venta, documento fiscal e integración ERP tienen estados distintos. No repetir un cargo incierto ni cambiar de proveedor para resolverlo automáticamente.', ['providers', 'resilience']);
  node('fiscal', 'Proveedor fiscal', 'Sistema externo', 'Contrato por país y modalidad', 'Emite o transmite documentos fiscales.', 'Autoridad y validez tributaria según régimen y proveedor.', 'Emitir offline exige modalidad y material fiscal válidos; no se promete universalmente.', 'Emisión, aceptación y transmisión se modelan por separado. No se inventa un proveedor común ni una capacidad de consulta o idempotencia no acreditada.', ['providers', 'proposal']);
  node('client', 'Cliente de caja', 'Contenedor', 'Angular + Tauri', 'Presenta caja y comandos del operador.', 'No posee otra base de ventas ni credenciales SQL.', 'Sin WAN usa la API por LAN. Sin LAN o backend, se detienen nuevos comandos dependientes.', 'Cliente instalado en cada puesto. Capacidades nativas por permisos; su registro técnico de periféricos no lo convierte en autoridad de ventas. Hardware y SDK requieren homologación.', ['technology', 'providers']);
  node('branchApi', 'Backend de sucursal', 'Contenedor', 'NestJS + Fastify / Node.js', 'Valida y confirma la operación local.', 'Única autoridad de escritura del negocio de sucursal; módulos internos, un proceso.', 'Opera por LAN con datos vigentes. Su caída exige recuperación del escritor autorizado.', 'Monolito modular: acceso, ventas, caja, precios/ofertas, pagos y fiscalidad. Confirma negocio y outbox en una misma transacción PostgreSQL. No hay un microservicio por módulo.');
  node('branchDb', 'Datos de sucursal', 'Contenedor de datos', 'PostgreSQL', 'Guarda negocio, outbox y espejo local.', 'Base compartida por la tienda, un primario autorizado. API escribe negocio; worker escribe su esquema técnico y publica espejos por un contrato acotado.', 'Persistencia local disponible sin WAN. No implica respaldo, alta disponibilidad ni recuperación automática.', 'Ventas, caja, pagos y evidencia fiscal son locales. Inbox, outbox, cursores y staging tienen restricciones y transacciones. Catálogo, precios y promociones son réplicas de lectura autorizadas, no maestros independientes.', ['proposal', 'resilience']);
  node('syncWorker', 'Sincronizador de sucursal', 'Contenedor', 'Worker TypeScript / Node.js', 'Entrega eventos y actualiza espejos.', 'Proceso supervisado; modifica datos técnicos y versiones de maestros, nunca venta libremente.', 'Retiene pendientes durables y reanuda al recuperar WAN; limita reintentos y trabajo en curso.', 'Envía lotes HTTPS desde outbox con identidad y cursor; procesa acuses posteriores a commit. Recibe deltas o carga snapshot por staging, watermark, checksum y activación atómica.');
  node('countryApi', 'API de país', 'Contenedor', 'NestJS + Fastify / Node.js', 'Aplica lotes y sirve publicaciones.', 'Autentica sucursal y país; confirma inbox, efecto local y outbox juntos antes del ACK de aplicación.', 'No participa en la transacción local de sucursal. Su caída genera atraso de sincronización.', 'Valida identidad y contrato; aplica el efecto/proyección local junto con inbox y outbox en un único commit antes de acusar aplicación. No basta guardar la recepción. El ACK no declara éxito de ERP, pago ni fiscalidad.');
  node('countryWorker', 'Workers de país', 'Contenedor', 'Workers NestJS / Node.js', 'Publica versiones e integra pendientes.', 'Consume outbox confirmada por país; publica maestros y mantiene proyecciones derivadas.', 'Avanza independientemente de tiendas desconectadas y limita fallos del ERP por país.', 'Procesa trabajo ya confirmado localmente para integración y conciliación; no difiere el efecto local requerido por el ACK de aplicación. Ingiere maestros autorizados, construye candidatas desde deltas o snapshots y valida su publicación.');
  node('countryDb', 'Datos operativos de país', 'Contenedor de datos', 'PostgreSQL', 'Consolida y conserva entrega durable.', 'Proyección de operaciones de sucursal; inbox, outbox, versiones y resultados de integración.', 'No sustituye la autoridad local ni habilita consumo concurrente offline de saldos globales.', 'Aislamiento lógico y recursos por país/entidad legal. Retención, backups y deduplicación deben cubrir el horizonte de replay y restauración. ACK de aplicación local no equivale a contabilización ERP.', ['proposal', 'resilience']);
  node('erpAdapter', 'Adaptador ERP / ACL', 'Contenedor', 'Proceso TypeScript / Node.js', 'Traduce contratos y concilia resultados.', 'Dueño del mapeo y referencias técnicas; ERP conserva su autoridad de negocio.', 'Desacoplado de la caja; conserva incertidumbre si no puede consultar un resultado.', 'ACL significa capa anticorrupción. Instancia/adaptador por país y ERP. Traduce identidades, documentos, moneda, impuestos, estados y errores; preserva destino y versión durante un cambio de ERP. El protocolo externo se valida por integración.', ['proposal', 'evidence', 'resilience']);
  node('entry', 'API de comandos', 'Componente', 'Controllers NestJS / Fastify', 'Valida entrada e identidad del comando.', 'Contrato del backend; no escribe tablas por fuera de los casos de uso.', 'API local por LAN; rechaza comandos cuando falta una capacidad requerida.', 'Autentica el puesto, valida esquema, propaga commandId y contexto de usuario/sucursal, aplica límites y entrega un resultado inequívoco o pendiente.');
  node('access', 'Acceso y permisos', 'Componente', 'Guards + servicios TypeScript', 'Autoriza usuario, perfil y sucursal.', 'Permisos y evidencia de sesión según política local autorizada.', 'La vigencia offline y revocación requieren política expresa; no acceso indefinido.', 'La identidad del usuario y la del puesto se verifican en comandos; el menú no constituye la frontera de autorización.');
  node('sales', 'Ventas y devoluciones', 'Componente', 'Módulo NestJS / TypeScript', 'Coordina el ciclo de la operación.', 'Escritor de ventas y devoluciones; conserva referencias, versiones y estados.', 'Permite solo operaciones soportadas por datos, límites y política vigentes.', 'Fija versión de precios al preparar la venta, registra intención y resultado de pagos y documentos; compensaciones y devoluciones son nuevas operaciones auditables.');
  node('pricing', 'Precios y ofertas', 'Componente', 'Motor TypeScript local', 'Cotiza sobre una versión vigente.', 'Lector del espejo PostgreSQL; no redefine el maestro corporativo.', 'No depende de una consulta de precio remoto para las ventas offline autorizadas.', 'Lee una versión completa validada e inmutable. Los deltas construyen una nueva candidata aislada a partir de la versión base; nunca parchean la activa. La cotización conserva versión, origen y reglas; la venta en curso no cambia de versión.', ['proposal', 'operations']);
  node('cash', 'Turnos y caja', 'Componente', 'Módulo NestJS / TypeScript', 'Controla apertura, movimientos y cierre.', 'Libro de movimientos y turnos de sucursal, con autorización y auditoría.', 'Opera localmente; excepciones y límites requieren una política aprobada.', 'Turno, saldo de efectivo, depósito y cierre son conceptos distintos de sesión de acceso. Los movimientos monetarios requieren identidad y transición validada.');
  node('payPort', 'Pagos y adaptadores', 'Componente', 'Puertos + TypeScript', 'Gestiona intentos y evidencia de pago.', 'Conserva identidad de intento y referencia del proveedor; no inventa resultado.', 'Si el proveedor no responde: pendiente/desconocido, consulta o resolución operativa.', 'No sostiene una transacción SQL abierta mientras espera el proveedor. Persiste intención antes de llamar y resultado después; procesos nativos auxiliares quedan sujetos al contrato de cada SDK.', ['providers', 'resilience']);
  node('fiscalPort', 'Fiscalidad y adaptadores', 'Componente', 'Puertos + TypeScript', 'Aplica modalidad fiscal por país.', 'Conserva identidad del documento y estados de emisión/aceptación/transmisión.', 'Solo modalidades legal y técnicamente habilitadas; falta de capacidad bloquea esa acción.', 'Separa confirmación de venta de validez fiscal. Un timeout fiscal mantiene la referencia original y la incertidumbre hasta consultar o conciliar.', ['providers', 'resilience']);
  node('unitOfWork', 'Persistencia transaccional', 'Componente', 'Repositorios TypeScript / SQL', 'Confirma negocio, auditoría y outbox.', 'Un commit sobre PostgreSQL de sucursal; restricciones e idempotencia de comandos.', 'La operación no se confirma si el commit falla. Falta de disco exige política de bloqueo.', 'Coordina cambios locales y outbox en la misma transacción. La transacción no engloba al proveedor externo ni al ERP; esos efectos tienen recuperación propia.', ['proposal', 'resilience']);
  node('schedule', 'Planificador y supervisor', 'Componente', 'Worker TypeScript', 'Admite trabajos con límites y ventanas.', 'Checkpoint y calendario por flujo; operación auditada.', 'Cierra admisión, drena o conserva checkpoint; no convierte timeout en rechazo.', 'Carga incremental continua según política, bulk programable y recuperación manual usan el mismo pipeline validado. Zona horaria IANA, límites, backoff y jitter son configuración explícita.', ['proposal', 'operations', 'resilience']);
  node('sender', 'Emisor de outbox', 'Componente', 'Worker TypeScript / HTTPS', 'Envía lotes con identidad estable.', 'Reintento de los mismos eventos; claim/lease técnico con recuperación.', 'Conserva cola durable; no elimina pendientes por pérdida de conexión.', 'Lee outbox confirmada, arma lotes acotados y mantiene commandId/eventId, país, sucursal, versión de contrato y secuencia. La entrega es al menos una vez, no exactly once universal.', ['proposal', 'resilience']);
  node('receiver', 'Receptor de deltas y acuses', 'Componente', 'Worker TypeScript / HTTPS', 'Valida contratos y cursores de entrega.', 'Distingue ACK de aplicación local de resultado financiero/fiscal/ERP.', 'Reanuda desde cursor durable; si hay huecos, solicita recuperación.', 'Los acuses del país llegan por respuestas o consulta autenticada. Un acuse perdido provoca replay con identidad original; nunca inventa un número ERP.', ['proposal', 'resilience']);
  node('dedup', 'Inbox y deduplicación', 'Componente', 'Transacciones SQL / TypeScript', 'Deduplica y prepara una candidata.', 'Inbox recibida, staging y cursor de recepción son durables; no equivalen a inbox aplicada ni cursor aplicado.', 'Replay repetido no duplica el efecto local. Restore exige conciliar evidencia.', 'Detecta duplicados, desorden y huecos. Aplica deltas a una candidata aislada y la entrega al validador. Descarga y preparación quedan fuera de la transacción final; al activar se confirman inbox aplicada, efecto y cursor aplicado juntos.', ['resilience', 'proposal']);
  node('snapshot', 'Carga de snapshot', 'Componente', 'Descarga HTTPS / TypeScript', 'Prepara una versión fuera de servicio.', 'Staging aislado; datasetVersion y watermark de origen identificables.', 'La versión activa sigue sirviendo mientras se descarga o falla una carga.', 'Carga masiva programada o manual; recibe manifiesto, versión, cobertura y watermark. Verifica chunks/checksum y recupera deltas posteriores antes de declarar una versión lista.', ['proposal', 'operations']);
  node('validation', 'Validador de publicación', 'Componente', 'Reglas TypeScript / SQL', 'Revisa integridad, cobertura y vigencia.', 'Impide activar lotes parciales o incompatibles.', 'Si no pasa validación se mantiene la versión previa, dentro de su vigencia autorizada.', 'Verifica checksum, referencias, monotonicidad, watermark, cantidad, fechas y compatibilidad fuera de la transacción final de activación. La candidata validada permanece identificada e inmutable; no se retiene una transacción durante la descarga.', ['proposal', 'operations']);
  node('activation', 'Activación de versión', 'Componente', 'Transacción SQL / TypeScript', 'Cambia atómicamente la versión activa.', 'Commit corto de inbox aplicada, efecto/puntero y cursor aplicado; conserva versiones aún referenciadas.', 'Nuevas ventas usan la versión activa; ventas abiertas conservan la versión fijada.', 'Recibe una candidata completa e inmutable validada, de snapshot o deltas. Recomprueba precondiciones y cambia el puntero en un commit corto, sin descarga ni validación pesada dentro de SQL. Recibido no significa aplicado.', ['proposal', 'operations', 'resilience']);
  node('device', 'Puente de periféricos', 'Contenedor condicional', 'Proceso nativo según SDK', 'Ejecuta capacidades del puesto.', 'Ejecuta identidad y autorización emitidas por backend; registro técnico de evidencia, sin base de ventas.', 'Una caída de LAN tras un cobro exige recuperar evidencia; no autoriza otro cobro.', 'El cliente transporta el comando autorizado por backend al agente; no inventa importe, permiso ni otro intento. Puede requerir .NET u otro runtime por contrato del proveedor. Se representa como límite por homologar, no como SDK aprobado.', ['providers', 'technology']);
  node('backup', 'Respaldo y recuperación', 'Infraestructura', 'Backups PostgreSQL / herramienta por definir', 'Conserva y ensaya restauraciones.', 'Operaciones define retención, RPO/RTO y reconstrucción de evidencia.', 'No es un segundo escritor activo ni garantiza continuidad inmediata.', 'Backups externos a la instancia, pruebas de restore y exclusión del escritor anterior. Una réplica no sustituye un backup; alta disponibilidad requiere diseño y ensayos separados.', ['resilience', 'proposal']);
  node('legend', 'Leyenda', 'Clave de lectura', 'Notación C4', 'Verde: POS. Azul/cilindro: datos. Gris: externo.', 'Límite discontinuo: sistema, proceso o nodo indicado en su título.', 'Flecha: iniciador, propósito y protocolo. Respuesta por el mismo contrato.', 'Persona: rol. Contenedor: aplicación o almacén. Componente: módulo en un proceso. LAN: red de tienda; WAN: enlace a país; ACL: capa anticorrupción; ACK: acuse durable.', ['c4']);

  const rel = (from, to, label) => ({ from, to, label });
  const views = [
    {
      id: 'context', key: 'c4-context', level: 'C1 · Contexto', title: 'El POS y su entorno',
      scope: 'Un sistema POS corporativo; personas y sistemas externos. Representación lógica aplicable a cada país.',
      note: 'La integración financiera, el precio autorizado, el pago y la fiscalidad tienen propietarios distintos. Los sistemas externos no se dan por homologados.',
      nodeIds: ['cashier','supervisor','support','pos','erp','masters','payments','fiscal'],
      boundaries: [],
      relationships: [rel('cashier','pos','Opera ventas y turnos · interfaz de caja'),rel('supervisor','pos','Autoriza y revisa · interfaz de operación'),rel('support','pos','Supervisa y recupera · herramientas autorizadas'),rel('masters','pos','Entrega datos y reglas · contrato por confirmar'),rel('pos','erp','Integra y concilia documentos · adaptador por país'),rel('pos','payments','Solicita pago y consulta resultado · API/SDK por validar'),rel('pos','fiscal','Solicita emisión/transmisión · contrato fiscal por validar')],
    },
    {
      id: 'containers', key: 'c4-containers', level: 'C2 · Contenedores', title: 'Aplicaciones, procesos y datos',
      scope: 'Interior del POS corporativo: cliente, sucursal y plataforma de país. Un contenedor C4 es una aplicación o almacén, no necesariamente Docker.',
      note: 'Una base y autoridad de negocio por sucursal; país mantiene proyecciones e integración. HTTPS con outbox/inbox durable es la base; RabbitMQ y Kafka no son requisitos.',
      nodeIds: ['cashier','client','device','branchApi','branchDb','syncWorker','countryApi','countryWorker','countryDb','erpAdapter','erp','masters','payments','fiscal'],
      boundaries: [{ id: 'systemScope', label: 'Sistema POS corporativo · propuesta', nodes: ['client','device','branchApi','branchDb','syncWorker','countryApi','countryWorker','countryDb','erpAdapter'] }],
      relationships: [rel('cashier','client','Opera caja · interfaz local'),rel('client','device','Transporta comando autorizado por backend / recoge evidencia · IPC o loopback'),rel('device','payments','Ejecuta terminal bancario si requiere agente · SDK/API homologado'),rel('client','branchApi','Envía comandos / consulta estado · HTTPS sobre LAN'),rel('branchApi','branchDb','Confirma negocio + outbox · SQL/transacción'),rel('branchApi','payments','Pago remoto directo si aplica · API HTTPS validada'),rel('branchApi','fiscal','Emisión / estado fiscal · puerto por país'),rel('syncWorker','branchDb','Lee outbox / escribe inbox, cursores y espejo · SQL'),rel('syncWorker','countryApi','Envía lotes / consulta deltas y acuses · HTTPS + cursor'),rel('countryApi','countryDb','Commit inbox + efecto + outbox antes del ACK de aplicación · SQL'),rel('countryWorker','countryDb','Consume outbox confirmada / publica versiones · SQL'),rel('countryWorker','masters','Obtiene cambios o carga masiva · contrato de origen por validar'),rel('countryWorker','erpAdapter','Entrega operación / consulta resultado · HTTPS interno'),rel('erpAdapter','countryDb','Guarda referencias y resultados de integración · SQL'),rel('erpAdapter','erp','Traduce y concilia · protocolo disponible por confirmar')],
    },
    {
      id: 'backend', key: 'c4-backend', level: 'C3 · Backend de sucursal', title: 'Dentro del monolito modular',
      scope: 'Un solo contenedor: backend de sucursal NestJS + Fastify. Los bloques interiores son componentes del mismo proceso.',
      note: 'Las llamadas internas son TypeScript; no se propone HTTP ni una base independiente entre módulos. Efectos externos tienen estados y recuperación separados.',
      nodeIds: ['client','entry','access','sales','pricing','cash','payPort','fiscalPort','unitOfWork','branchDb','payments','fiscal'],
      boundaries: [{ id: 'backendScope', label: 'Backend de sucursal · UN proceso<br/>Contenedor NestJS + Fastify', nodes: ['entry','access','sales','pricing','cash','payPort','fiscalPort','unitOfWork'] }],
      relationships: [rel('client','entry','Comando con identidad estable · HTTPS/LAN'),rel('entry','access','Comprueba permiso y contexto · llamada TypeScript'),rel('entry','sales','Ejecuta venta/devolución · llamada TypeScript'),rel('entry','cash','Abre, mueve o cierra caja · llamada TypeScript'),rel('sales','pricing','Cotiza y fija versión · llamada TypeScript'),rel('sales','cash','Valida turno · TypeScript'),rel('sales','payPort','Coordina intento y resultado · llamada TypeScript'),rel('sales','fiscalPort','Coordina documento y estado · llamada TypeScript'),rel('sales','unitOfWork','Persiste operación y outbox · llamada TypeScript'),rel('cash','unitOfWork','Persiste movimientos y auditoría · llamada TypeScript'),rel('pricing','unitOfWork','Lee versión local autorizada · repositorio TypeScript'),rel('payPort','unitOfWork','Registra intención y resultado por separado · TypeScript'),rel('fiscalPort','unitOfWork','Registra referencia y resultado · TypeScript'),rel('unitOfWork','branchDb','Commit local atómico · SQL'),rel('payPort','payments','Invoca capacidad homologada · API/SDK'),rel('fiscalPort','fiscal','Emite/consulta · API/SDK')],
    },
    {
      id: 'sync', key: 'c4-sync', level: 'C3 · Sincronizador', title: 'Entrega durable y precios locales',
      scope: 'Un solo contenedor: worker de sincronización de sucursal. La API/DB de país y PostgreSQL local son colaboradores externos al proceso.',
      note: 'Deltas y cargas completas comparten validación. Snapshot + watermark + staging + checksum + activación atómica; las ventas abiertas mantienen su versión.',
      nodeIds: ['schedule','sender','receiver','dedup','snapshot','validation','activation','branchDb','countryApi'],
      boundaries: [{ id: 'syncScope', label: 'Sincronizador · UN proceso<br/>Contenedor worker Node.js', nodes: ['schedule','sender','receiver','dedup','snapshot','validation','activation'] }],
      relationships: [rel('schedule','sender','Admite lote / reintento acotado · TypeScript'),rel('sender','branchDb','Claim y lectura de outbox · SQL'),rel('sender','countryApi','Envía lote con eventId/contrato · HTTPS'),rel('schedule','receiver','Programa consulta incremental · TypeScript'),rel('receiver','countryApi','Consulta acuses y deltas con cursor · HTTPS'),rel('receiver','dedup','Entrega unidad validada · TypeScript'),rel('dedup','branchDb','Guarda recibido/staging; no avanza aplicado · SQL'),rel('schedule','snapshot','Carga programada o recuperación manual · TypeScript'),rel('snapshot','countryApi','Descarga manifiesto/chunks y watermark · HTTPS'),rel('snapshot','branchDb','Guarda staging aislado · SQL'),rel('snapshot','validation','Solicita validación de versión completa · TypeScript'),rel('validation','branchDb','Verifica checksum, referencias y vigencia · SQL'),rel('validation','activation','Autoriza versión y watermark válidos · TypeScript'),rel('dedup','validation','Entrega candidata completa desde deltas · TypeScript'),rel('activation','branchDb','Commit corto: inbox aplicada + versión + cursor aplicado · SQL')],
    },
    {
      id: 'deployment', key: 'c4-deployment', level: 'Complemento · Despliegue', title: 'Dónde corre cada pieza',
      scope: 'Entorno objetivo de referencia: una tienda y una plataforma por país. No describe servidores o proveedores cloud ya contratados.',
      note: 'Varias cajas comparten servidor y PostgreSQL de sucursal. Sin WAN puede continuar la operación autorizada; sin LAN o escritor, no se crea otra autoridad en cada puesto.',
      nodeIds: ['client','device','branchApi','branchDb','syncWorker','countryApi','countryWorker','countryDb','erpAdapter','erp','payments','fiscal','backup'],
      boundaries: [
        { id: 'terminalNode', label: 'Puestos POS x N · Nodo<br/>Sistema operativo por inventariar', nodes: ['client','device'] },
        { id: 'serverNode', label: 'Servidor de sucursal · Nodo<br/>Entorno de ejecución por homologar', nodes: ['branchApi','syncWorker','branchDb'] },
        { id: 'countryNode', label: 'Plataforma de país · Nodo<br/>Alojamiento por decidir', nodes: ['countryApi','countryWorker','erpAdapter','countryDb'] },
      ],
      relationships: [rel('client','branchApi','Comandos autenticados · HTTPS/LAN'),rel('client','device','Comando autorizado por backend · IPC/loopback por homologar'),rel('branchApi','branchDb','Negocio + outbox · SQL local'),rel('syncWorker','branchDb','Pendientes, cursores y espejo · SQL local'),rel('syncWorker','countryApi','Lotes, deltas y snapshots · HTTPS/WAN'),rel('countryApi','countryDb','Commit inbox + efecto + outbox antes de ACK · SQL'),rel('countryWorker','countryDb','Outbox confirmada / publicaciones · SQL'),rel('countryWorker','erpAdapter','Contrato canónico · HTTPS interno'),rel('erpAdapter','erp','Traducción por país · interfaz ERP por validar'),rel('erpAdapter','countryDb','Resultados y referencias · SQL'),rel('device','payments','Terminal/pago · SDK o API homologado'),rel('branchApi','fiscal','Emisión/transmisión · modalidad por homologar'),rel('branchDb','backup','Copia y evidencia de restore · mecanismo por definir'),rel('countryDb','backup','Copia y retención por país · mecanismo por definir')],
    },
  ];
  for (const view of views) view.nodeIds.push('legend');
  window.POS_C4 = {
    views, nodes, sources,
    legend: [
      'Persona: rol humano. Sistema externo: responsabilidad fuera del POS.',
      'Contenedor: aplicación/proceso o almacén de datos. Componente: módulo dentro de un proceso.',
      'Verde: software POS. Azul/cilindro: datos. Gris: externo. Borde discontinuo: límite del alcance.',
      'Cada flecha indica quién inicia la relación, con propósito y protocolo; la respuesta viaja por el mismo contrato.',
      'LAN: red de sucursal. WAN: enlace a país. ACL: capa anticorrupción. ACK: acuse de aplicación tras commit durable.',
      'Todo es propuesta salvo antecedentes expresamente señalados. Despliegue es complementario; no es el nivel C4 de código.',
    ],
  };
})();
