/* Assemble static presentation and linked evidence. No dependencies or corporate code. */
'use strict';
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '../..');
const output = path.resolve(root, 'public');
const files = [];

function collect(directory, accept) {
  for (const entry of fs.readdirSync(path.join(root, directory), {withFileTypes:true})) {
    const relative = path.posix.join(directory, entry.name);
    if (entry.isSymbolicLink()) throw new Error(`Refusing symlink: ${relative}`);
    if (entry.isDirectory()) collect(relative, accept);
    else if (entry.isFile() && accept(relative)) files.push(relative);
  }
}

// Keep the original directory layout so ../docs and ../presentation links work.
collect('docs', file => /\.(md|png|jpe?g|svg|webp|pdf|pptx)$/i.test(file) || (file.startsWith('docs/diagramas-excalidraw/') && /\.(html|excalidraw|zip)$/.test(file)));
for (const entry of fs.readdirSync(path.join(root, 'presentation'), {withFileTypes:true})) {
  if (entry.isFile() && /\.(html|css|js|md)$/.test(entry.name)) files.push('presentation/' + entry.name);
}
collect('presentation/diagrams', file => file.endsWith('.mmd'));
collect('presentation/architecture-diagrams', file => /^presentation\/architecture-diagrams\/[^/]+\.svg$/.test(file));
files.push('README.md');
for (const name of ['concentrador-ingress-evidence.json', 'concentrador-masters-evidence.json']) {
  files.push('tools/' + name);
}

// Verify the exact disposable output before any recursive cleanup.
if (path.dirname(output) !== root || path.basename(output) !== 'public') throw new Error('Invalid output directory');
if (fs.existsSync(output)) {
  const stat = fs.lstatSync(output);
  if (!stat.isDirectory() || stat.isSymbolicLink()) throw new Error('Output must be a regular directory');
  const marker = path.join(output, '.pos-atlas-build');
  if (!fs.existsSync(marker)) throw new Error('Refusing to replace public/ without the build marker');
  fs.rmSync(output, {recursive:true});
}
fs.mkdirSync(output);
fs.writeFileSync(path.join(output, '.pos-atlas-build'), 'Generated by presentation/tools/build-vercel.cjs\n');
for (const file of files) {
  const source = path.join(root, file);
  if (!fs.lstatSync(source).isFile()) throw new Error(`Expected regular file: ${file}`);
  const destination = path.join(output, file);
  fs.mkdirSync(path.dirname(destination), {recursive:true});
  fs.copyFileSync(source, destination);
}
console.log(`Static output: ${files.length} files in public/ (presentation, documents and linked evidence).`);
